[package]
name = "ignore-python"
version = "0.3.3"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ignore"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.28.3"
ignore-rust = { version = "0.4.25", package = "ignore" }
