[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
    { id = "end-of-file-fixer" },
    { id = "trailing-whitespace" },
    { id = "name-tests-test" },
    { id = "check-toml" },
]

[[repos]]
repo = "https://github.com/abravalheri/validate-pyproject"
rev = "v0.25"
hooks = [{ id = "validate-pyproject" }]

[[repos]]
repo = "https://github.com/crate-ci/typos"
rev = "v1.44.0"
hooks = [{ id = "typos" }]

[[repos]]
repo = "https://github.com/psf/black"
rev = "26.3.0"
hooks = [{ id = "black" }]

[[repos]]
repo = "local"
hooks = [
    {
		id = "rustfmt",
		name = "rustfmt",
		entry = "rustfmt",
		language = "system",
		files = "\\.rs$",
    }
]
